export enum EMapAction {
  GET_PLACES = "GET_PLACES",
  GET_PLACES_REQUEST = "GET_PLACES_REQUEST",
  GET_PLACES_FAILURE = "GET_PLACES_FAILURE",
  ADD_PLACE = "ADD_PLACE",
  ADD_PLACE_REQUEST = "ADD_PLACE_REQUEST",
  ADD_PLACE_FAILURE = "ADD_PLACE_FAILURE",
  DELETE_PLACE = "DELETE_PLACE",
  DELETE_PLACE_REQUEST = "DELETE_PLACE_REQUEST",
  DELETE_PLACE_FAILURE = "DELETE_PLACE_FAILURE",
  SET_CENTER = "SET_CENTER",
}
